-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 26, 2024 at 01:29 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.0.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `pos_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `price` double NOT NULL,
  `category` varchar(255) DEFAULT NULL,
  `path` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `name`, `description`, `price`, `category`, `path`) VALUES
(15743580, 'Corduroy Croptop Jacket', 'The yellow croptop jacket with buttons and pockets offers a chic and versatile addition to any wardrobe, providing both style and functionality in one vibrant piece.', 312.21, 'Womens', 'women jacket.png'),
(15743581, 'Paul Black Trouser', 'The black trousers for men are a classic wardrobe staple, offering timeless style and versatility suitable for both formal and casual settings, ensuring a sophisticated look with every wear.', 500, 'Mens', 'men classy pants.png'),
(15743582, 'Men Bomber Jacket', 'The men\'s bomber jacket is a timeless outerwear piece characterized by its iconic silhouette, featuring a zip-front closure, ribbed cuffs and hem, and a versatile design suitable for casual and semi-formal occasions, providing both style and comfort effortlessly.', 200, 'Mens', 'men bomber jacket.png'),
(15743583, 'Red Dress', 'The red minidress is a striking and bold garment that exudes confidence and glamour, featuring a flirtatious silhouette with a hemline above the knee, perfect for making a statement at any special event or night out.', 250.5, 'Womens', 'women minidress.png'),
(15743584, 'Flare Jeans', 'Flare jeans are a retro-inspired denim style characterized by their fitted hips and thighs that gradually widen into a dramatic flare below the knee, offering a flattering and effortlessly chic silhouette reminiscent of 1970s fashion.', 150, 'Womens', 'women pants.png'),
(15743585, 'Heart Graphic Tshirt', 'The heart graphic t-shirt is a playful and expressive garment featuring a vibrant or subtle heart design printed on the front, adding a touch of charm and personality to casual outfits, perfect for showcasing love or adding a whimsical element to everyday wear.', 100, 'Womens', 'women tshirt hearrttt.png'),
(15743586, 'Polo Shirt', 'The polo shirt is a classic and versatile garment, featuring a collar, buttoned placket, and short sleeves, offering a timeless and sophisticated look suitable for both casual and semi-formal occasions, providing comfort and style with its breathable fabric and understated elegance.', 199, 'Womens', 'women polo.png'),
(15743587, 'Pattern Playsuit', 'The pattern playsuit is a fun and stylish one-piece garment featuring a variety of playful prints and designs, offering a chic and effortless outfit solution perfect for warmer weather or casual outings, combining comfort with trend-forward aesthetics.', 399.5, 'Womens', 'women dress aesthetic.png'),
(15743588, 'Bomber Croptop Jacket', 'The bomber crop top jacket is a trendy fusion of two iconic styles, featuring the classic bomber jacket silhouette with a cropped length, offering a contemporary and edgy look that\'s perfect for layering over high-waisted bottoms or pairing with dresses for a modern twist on casual or streetwear fashion.', 499.5, 'Womens', 'women bomber jacket.png'),
(15743589, 'Beige Trouser', 'The beige trousers are a versatile wardrobe staple, offering a timeless and sophisticated option suitable for both casual and formal settings, featuring a neutral hue that effortlessly complements a variety of outfits and occasions, ensuring a polished and refined look with every wear.', 400, 'Womens', 'women beige trouser.png'),
(15743590, 'Skeleton Graphic Tshirt', 'The skeleton graphic t-shirt is a bold and edgy garment featuring a striking skeletal design printed on the front, adding a unique and alternative flair to casual outfits, perfect for those who embrace a rebellious or avant-garde aesthetic.', 129.5, 'Womens', 'women tshirt.png'),
(15743591, 'Vintage Jeans', 'Men\'s vintage jeans offer a timeless and rugged style inspired by classic denim designs from past decades, characterized by their distressed detailing, relaxed fit, and worn-in look, providing a nostalgic and effortlessly cool vibe that pairs well with a variety of casual outfits.', 699, 'Mens', 'men jeans.png'),
(15743592, 'Mark Jogger Pants', 'Jogger pants are a comfortable and versatile bottomwear option, featuring a tapered fit, elasticized cuffs at the ankles, and an adjustable drawstring waist, offering a stylish blend of athletic and casual aesthetics that\'s perfect for both lounging at home and running errands around town.', 350, 'Mens', 'men jogger pants.png'),
(15743593, 'Beige Pants', 'Men\'s beige pants offer a timeless and versatile option for casual and semi-formal occasions, featuring a neutral hue that pairs effortlessly with a variety of colors and patterns, providing a sophisticated and polished look suitable for both work and leisure.', 350, 'Mens', 'men pants beige.png'),
(15743594, 'Black Polo', 'The black polo shirt for men is a classic wardrobe staple, characterized by its collared neckline, buttoned placket, and short sleeves, offering a timeless and versatile option suitable for casual outings, sports activities, or semi-formal occasions, providing a sleek and effortlessly stylish look with its neutral color and understated design.', 199.5, 'Mens', 'men polo black.jpg'),
(15743595, 'Stripes Polo ', 'The striped polo shirt for men is a stylish and timeless garment featuring horizontal or vertical stripes, adding a touch of sophistication and visual interest to casual outfits, perfect for achieving a smart-casual look with its classic polo silhouette and versatile design.', 249, 'Mens', 'men polo stripes.png'),
(15743596, 'Cars Graphic Tshirt', 'The cars graphic t-shirt is a vibrant and playful garment featuring colorful illustrations or images of cars, perfect for automotive enthusiasts or anyone looking to add a fun and casual flair to their outfit, offering a dynamic and eye-catching look that\'s sure to turn heads.', 199, 'Mens', 'men tshirt.png'),
(15743597, 'Nirvana Tshirt', 'The Nirvana t-shirt is an iconic and timeless piece of band merchandise featuring the band\'s logo, album artwork, or other imagery associated with the legendary grunge band Nirvana, offering fans a stylish and nostalgic way to pay homage to their music and legacy while adding a touch of rock-inspired edge to their wardrobe.', 200, 'Mens', 'men tshirtt.png'),
(15743598, 'Dryfit Tshirt', 'The DryFit t-shirt for men is a performance-oriented garment crafted from moisture-wicking fabric, designed to keep the wearer dry and comfortable during intense workouts or outdoor activities by quickly wicking away sweat, offering breathability and freedom of movement, making it an ideal choice for active individuals seeking comfort and performance in their athletic wear.', 159, 'Mens', 'men dryfit.png'),
(15743599, 'Blue Corset Dress', 'A stunning blue corset dress, with its sculpted bodice, flowing skirt, and captivating hue, exudes elegance and allure for any occasion.', 500, 'Womens', 'blue.png'),
(15743600, 'Aesthetic Maxi Dress', 'An aesthetic maxi dress, with its flowing silhouette, soft fabrics, and whimsical details, epitomizes effortless bohemian chic.', 1000, 'Womens', 'cute.png'),
(15743601, 'Flower Cardigan', 'A flower cardigan, adorned with delicate floral motifs, adds a charming touch of femininity and warmth to any outfit.', 799, 'Womens', 'WOMEN SUNSHINE.png'),
(15743602, 'Black Polo Shirt', 'A men\'s black polo, with its timeless style and versatility, offers a classic yet sleek option for casual or semi-formal occasions.', 499, 'Mens', 'Black polo.png'),
(15743603, 'Black Leather Jacket', 'Men\'s leather garments, ranging from jackets to trousers, exude a rugged yet sophisticated charm, offering timeless style and durability with a hint of edgy elegance.', 1500, 'Mens', 'men leather.png'),
(15743604, 'Cute Jacket', 'A cute jacket, with its playful design, flattering fit, and charming details, adds a touch of whimsy and style to any outfit.', 999, 'Womens', 'jacket.png'),
(15743605, 'White Polo Shirt', 'A white polo shirt, crisp and classic, epitomizes timeless sophistication and effortless style for any occasion.', 599, 'Mens', 'polo zip.png'),
(15743606, 'Cargo Pants', 'Cargo pants, with their functional pockets and rugged aesthetic, offer practicality and versatility, perfect for both outdoor adventures and urban exploration.', 800, 'Mens', 'cargo pants.png'),
(15743607, 'PoloShirt', 'A polo shirt, with its collared neckline and sporty elegance, strikes the perfect balance between casual comfort and refined style, making it a wardrobe essential for any occasion.', 399, 'Womens', 'zip poloshirt.png'),
(15743608, 'Black Maxidress', 'A black maxidress, with its flowing silhouette and timeless elegance, exudes sophistication and versatility for any formal or casual affair.', 999, 'Womens', 'black maxidress.png'),
(15743609, 'Longsleeve', 'A black long-sleeve shirt, with its sleek and versatile design, offers understated elegance and timeless style for any occasion, effortlessly blending sophistication with comfort.', 546, 'Mens', 'men longsleeve.png'),
(15743610, 'Blue Polo', 'A blue polo shirt, with its classic yet vibrant style, offers a versatile and polished look suitable for both casual outings and semi-formal occasions.', 899, 'Mens', 'blue.png'),
(15743611, 'Brown Longsleeve', 'A brown long-sleeve shirt, with its warm and earthy tone, adds a touch of rustic charm and versatility to any outfit, perfect for casual or outdoor settings.', 600, 'Mens', 'basta.png'),
(15743612, 'Blue Tube Minidress', 'A blue tube minidress, with its sleek and flirty design, exudes confidence and style, making it the perfect choice for a night out or special occasion.', 1200, 'Womens', 'blue minidress.png'),
(15743613, 'White Corset Dress', 'A white corset dress, with its structured bodice and elegant silhouette, emanates sophistication and timeless charm, making it a stunning choice for weddings or formal events.', 999, 'Womens', 'white.png'),
(15743614, 'White Tshirt', 'A white T-shirt, with its simplicity and versatility, serves as a timeless wardrobe staple, offering comfort and effortless style for any casual occasion.', 450, 'Womens', 'white tee.png'),
(15743615, 'Graphic Tshirt', 'A graphic T-shirt, adorned with vibrant designs or witty slogans, adds personality and flair to any casual ensemble, making it a stylish choice for expressing individuality and creativity.', 500, 'Womens', 'sunshine.png'),
(15743616, 'Stripes Tshirt', 'A striped T-shirt, with its timeless pattern and casual charm, brings a touch of classic sophistication to any outfit, effortlessly elevating your everyday style with a hint of nautical flair.', 299, 'Womens', 'stripes.png'),
(15743617, 'Women Nirvana Tshirt', 'Nirvana was an iconic American rock band from the 1990s, known for their influential sound, led by the late Kurt Cobain, and their album \"Nevermind,\" which propelled them to global fame, shaping the landscape of alternative rock music.', 399, 'Womens', 'nirvana.png'),
(15743618, 'Blue Tshirt', 'A blue T-shirt, with its versatile and understated style, offers a timeless and effortlessly cool option for casual wear, perfect for any occasion.', 399, 'Mens', 'blue tshirt.png'),
(15743619, 'Gray Tshirt', 'A gray T-shirt, with its subtle and versatile hue, provides a classic and understated option for casual attire, offering effortless style and comfort for everyday wear.', 400, 'Mens', 'gray.png'),
(15743620, 'White T-shirt ', 'A white T-shirt, with its clean and classic appeal, serves as a timeless wardrobe essential, offering versatility and simplicity for a wide range of outfits and occasions.', 400, 'Mens', 'white tee.png'),
(15743621, 'Pink sunglasses', 'Pink sunglasses add a vibrant and playful touch to any ensemble while offering protection from the sun\'s glare.', 245, 'Womens/Accessories', 'pink sunglasses.png'),
(15743622, 'Aesthetic Black Sunglass', 'Black glasses exude a timeless and sophisticated aesthetic, effortlessly adding an intellectual edge to any look with their classic appeal.', 349, 'Mens/Accessories', 'glasses.png'),
(15743623, 'Unisex Sunglass', 'Unisex sunglasses offer versatile style options suitable for anyone, regardless of gender, providing a fashionable and inclusive accessory for all.', 299, 'Accessories', 'ehe.png'),
(15743624, 'Y2K glasses', 'Y2K glasses, inspired by the early 2000s fashion, often feature sleek, futuristic designs with small frames, tinted lenses, and bold colors, adding a nostalgic yet trendy touch to any outfit.', 345, 'Accessories', 'weh.png'),
(15743625, 'Silver Bracelet', 'A silver bracelet is a timeless accessory, offering understated elegance and versatility that can complement both casual and formal attire with its sleek metallic shine.', 200, 'Mens/Accessories', 'silver.png'),
(15743626, 'Black Bracelet', 'A black bracelet brings a touch of sophistication and versatility to any ensemble, effortlessly blending with various styles and occasions, whether it\'s a sleek leather cuff or a minimalist beaded design.', 200, 'Mens/Accessories', 'lack.png'),
(15743627, 'Lucky Bracelet', 'A lucky bracelet often carries symbolic charms or beads believed to bring good fortune or protection, serving as a meaningful and personal accessory that can inspire positivity and confidence in its wearer.', 250, 'Womens/Accessories', 'brace.png'),
(15743628, 'Chain Bracelet', 'A chain bracelet is a stylish and versatile accessory, featuring interlocking links that can range from delicate and dainty to bold and chunky, adding a touch of edgy sophistication to any outfit.', 250, 'Womens/Accessories', 'bracelet.png'),
(15743629, 'Square shaped watch', 'A square watch offers a unique and modern take on traditional timepieces, with its distinctive shape adding a sleek and contemporary touch to your wrist, making a subtle yet stylish statement.', 999, 'Accessories', 'watch.png'),
(15743630, 'Rounded Shaped Watch', 'A round watch exudes timeless elegance and classic sophistication, with its traditional shape serving as a versatile accessory that complements any outfit or occasion, epitomizing refined style and functionality.', 999, 'Accessories', 'round.png'),
(15743631, 'Brown Watch', 'A brown watch exudes warmth and versatility, offering a classic yet distinctive alternative to traditional black or silver timepieces, making it a stylish choice for both casual and formal wear, especially with its ability to complement earthy tones and add a touch of sophistication to any ensemble.', 1500, 'Accessories', 'brown.png'),
(15743632, 'Butterfly Watch', 'A butterfly watch features a whimsical and feminine design, often with a dial or strap adorned with butterfly motifs, symbolizing beauty, transformation, and freedom, making it a charming and enchanting accessory for those who appreciate nature-inspired elegance.', 999, 'Womens/Accessories', 'butterfly.png'),
(15743633, 'Heart Watch', 'A heart watch showcases a romantic and playful design, with its dial or strap adorned with heart-shaped elements, symbolizing love, affection, and passion, making it a delightful and sentimental accessory for expressing heartfelt sentiments and adding a touch of sweetness to any outfit.', 1000, 'Womens/Accessories', 'heart.png'),
(15743634, 'Azure Breeze Tee', 'The Azure Breeze Tee is a classic blue t-shirt made from soft, high-quality cotton, featuring a flattering crew neckline and a relaxed fit. Its vibrant azure blue color adds a touch of style to any casual outfit.', 250, 'Womens', '2(7).png'),
(15743635, 'Crystal Cove Tee', 'The Crystal Cove Tee is a timeless white t-shirt crafted from ultra-soft, breathable cotton with a classic crew neckline and a comfortable, relaxed fit. Perfect for any casual occasion, its clean, crisp design pairs effortlessly with any outfit.', 199, 'Womens', '5(3).png'),
(15743636, 'Sunset Drift Tee', 'The Sunset Drift Tee is an oversized orange t-shirt made from soft, breathable fabric, featuring a relaxed fit and a casual drop-shoulder design. Its vibrant color and comfortable style make it a perfect statement piece for laid-back, everyday wear.', 199, 'Womens', '9(2).png'),
(15743637, 'Lush Blossom Crop', 'The Lush Blossom Crop is a chic puff sleeve crop top made from lightweight, airy fabric, featuring a flattering square neckline and elasticated hem for a perfect fit. Its stylish puff sleeves add a touch of romance and elegance, making it ideal for both casual and dressy occasions.\r\n', 150, 'Womens', '13(2).png'),
(15743638, ' Citrus Layered Vest Set', 'The Citrus Layered Vest Set includes a vibrant orange t-shirt paired with a sleek, tailored vest, offering a stylish and modern layered look. This combination blends casual comfort with a touch of sophistication, perfect for versatile, everyday wear.', 599, 'Womens', '17(2).png'),
(15743639, 'Yamaha Racer Polo', ' The Yamaha Racer Polo is a sporty polo shirt for boys, featuring the iconic Yamaha logo and racing-inspired design elements. Made from durable, breathable fabric, it offers comfort and style for young motorsport enthusiasts.', 399, 'Mens', '21(2).png'),
(15743640, 'Polka Dot Charm Tube Dress', 'The Polka Dot Charm Tube Dress is a playful and stylish dress featuring a classic polka dot pattern and a flattering strapless design. Made from lightweight, stretchy fabric, it offers a comfortable fit and a chic silhouette perfect for summer outings or casual events.', 399, 'Womens', '25(2).png'),
(15743641, 'Espresso Classic Polo', 'The Espresso Classic Polo is a sophisticated brown collared t-shirt for men, crafted from soft, breathable cotton with a tailored fit. Its rich espresso color and classic design make it perfect for both casual and semi-formal occasions.', 299, 'Mens', '29(2).png'),
(15743642, 'Burgundy Bliss Long Sleeve', 'The Burgundy Bliss Long Sleeve is a stylish and versatile maroon long sleeve shirt, crafted from soft, cozy fabric for all-day comfort. Its rich burgundy hue adds a touch of sophistication, making it perfect for layering or wearing on its own for a sleek, polished look.\r\n\r\n\r\n\r\n\r\n\r\n', 249, 'Womens', '33(2).png'),
(15743643, 'Sunbeam Comfort Tee', 'The Sunbeam Comfort Tee is a vibrant yellow t-shirt for men, made from soft, breathable cotton for all-day wearability. Its sunny hue adds a cheerful pop of color to any outfit, while the classic crew neckline and relaxed fit ensure both style and comfort.', 149, 'Mens', '37(1).png'),
(15743644, 'Misty Grey Elegance Dress', 'The Misty Grey Elegance Dress exudes sophistication with its understated yet refined design. Crafted from a luxurious blend of fabrics, this gray dress features a tailored silhouette that flatters every curve. Perfect for both formal events and casual outings, its versatile style makes it a wardrobe staple for any occasion.', 449, 'Womens', '41(1).png'),
(15743645, ' Azure Breeze Cropped Long Sleeve', 'The Azure Breeze Cropped Long Sleeve is a chic and versatile top crafted from soft, stretchy fabric in a captivating shade of blue. With its flattering cropped silhouette and long sleeves, it offers both style and comfort. Whether paired with high-waisted jeans for a casual look or a skirt for a more polished ensemble, this top adds a touch of effortless elegance to any outfit.', 299, 'Womens', '45(1).png'),
(15743646, 'Petal Pink Serenity Maxi Dress', 'The Petal Pink Serenity Maxi Dress is an epitome of grace and charm, featuring a soft pink hue that exudes femininity. This dress boasts a flowing silhouette that elegantly drapes the body, while the maxi length adds a touch of sophistication. Perfect for special occasions or a romantic evening out, it\'s a timeless piece that effortlessly captures attention and radiates elegance.\r\n', 345, 'Womens', '49(1).png'),
(15743647, 'Oceanic Skyline High-Waist Pants', ' The Oceanic Skyline High-Waist Pants are a sleek and versatile wardrobe staple in a serene shade of blue reminiscent of the vast sky meeting the ocean. With a flattering high-waisted design, these pants elongate the legs for a polished look. Perfect for both casual outings and formal occasions, they offer comfort and style in equal measure, effortlessly elevating any ensemble.', 300, 'Womens', '1(10).png'),
(15743648, 'Sky Breeze Denim Jorts', 'Embrace casual chic with our Sky Breeze Denim Jorts, featuring a refreshing sky blue hue reminiscent of clear summer skies. These jean shorts boast a classic silhouette with a relaxed fit and frayed hem for a laid-back vibe. Whether you\'re strolling along the beach or enjoying a weekend brunch, these jorts are the perfect blend of comfort and style for warm-weather adventures.', 200, 'Mens', '7(4).png'),
(15743649, 'AeroGlide Utility Pants', 'Introducing our AeroGlide Utility Pants, inspired by the functionality of parachute pants with a modern twist. Crafted from lightweight, durable fabric, these pants offer freedom of movement and versatility for any activity. With ample pockets and adjustable straps, they seamlessly blend style and functionality, perfect for urban explorers and outdoor enthusiasts alike.', 200, 'Mens', '9(3).png'),
(15743650, 'Shadow Sprint Joggers', 'Step into comfort and style with our Shadow Sprint Joggers, designed to elevate your athleisure game. Crafted from premium black fabric, these joggers offer a sleek silhouette with a relaxed fit and tapered legs. Whether you\'re hitting the gym or running errands, the Shadow Sprint Joggers provide unparalleled comfort and versatility for every occasion.', 300, 'Mens', '12(3).png'),
(15743651, 'Skyward Soar Parachute Pants', 'Elevate your style with our Skyward Soar Parachute Pants, designed for the modern woman who embraces both comfort and fashion. Crafted from lightweight, flowy fabric, these pants feature a high-rise waist and billowy legs for a relaxed yet chic silhouette. With their versatile design and effortless elegance, the Skyward Soar Parachute Pants are perfect for a casual day out or a stylish evening affair.', 235, 'Womens', '13(3).png'),
(15743652, 'Twilight Temptation Miniskirt', 'The Twilight Temptation Miniskirt is a flirtatious and versatile addition to your wardrobe, designed to make a statement wherever you go. Crafted from soft, stretchy fabric, this skirt hugs your curves while offering comfort and flexibility. Its mini length and figure-flattering silhouette ensure you stand out in any crowd, whether paired with a casual tee for a daytime look or dressed up with heels for a night on the town.', 175, 'Womens', '17(3).png'),
(15743653, ' Midnight Maven Tailored Trousers', 'Elevate your ensemble with our Midnight Maven Tailored Trousers, crafted for the sophisticated woman who values both style and comfort. Made from high-quality fabric with a touch of stretch, these trousers feature a sleek, tailored silhouette that flatters your figure. Whether paired with a blouse for the office or a statement top for a night out, the Midnight Maven Tailored Trousers exude timeless elegance and versatility for any occasion.', 475, 'Mens', '21(3).png'),
(15743654, 'Luna Tailored Trousers', 'Introducing Luna Tailored Trousers, the epitome of sophistication and versatility for the modern woman. Crafted from premium fabric with a hint of stretch, these trousers offer a flattering fit that accentuates your curves while providing all-day comfort. With a sleek silhouette and classic design, they effortlessly transition from office meetings to evening engagements, ensuring you exude confidence and style wherever you go.', 375, 'Womens', '23(3).png'),
(15743655, 'Sand Dune Tailored Trousers', 'Embrace timeless elegance with our Sand Dune Tailored Trousers, crafted to elevate your everyday style. Made from a luxurious blend of fabrics, these pants feature a flattering high-rise waist and a tapered leg silhouette for a sleek and sophisticated look. The neutral beige hue complements any outfit, while the impeccable tailoring ensures a perfect fit. Whether you\'re at the office or out for brunch, the Sand Dune Tailored Trousers exude effortless chic and versatility.', 355, 'Womens', '25(3).png'),
(15743656, 'Sandstone Classic Chinos', 'Elevate your casual ensemble with our Sandstone Classic Chinos, crafted from premium beige fabric for a timeless look. These pants feature a tailored fit and a hint of stretch for all-day comfort and versatility. Whether paired with a crisp shirt for a polished appearance or dressed down with a casual tee, the Sandstone Classic Chinos are the perfect choice for any occasion, exuding effortless style and sophistication.', 355, 'Mens', '27(3).png'),
(15743657, 'Desert Dunes Utility Jacket', ' Embrace rugged elegance with our Desert Dunes Utility Jacket, crafted in a versatile beige hue reminiscent of sun-kissed sands. This jacket features a classic silhouette with multiple pockets for functionality and style. Whether you\'re exploring the great outdoors or navigating city streets, the Desert Dunes Utility Jacket offers both warmth and flair, making it a staple piece for your wardrobe year-round.', 450, 'Womens', '53(2).png'),
(15743658, 'Rosevine Classic Polo', 'The Rosevine Classic Polo is a sophisticated yet stylish option for men, featuring an embroidered rose motif on the chest. Crafted from high-quality cotton, this polo offers a comfortable fit and timeless style. Perfect for both casual and semi-formal occasions, the Rosevine Classic Polo adds a touch of elegance to any outfit.', 275, 'Mens', '57(1).png'),
(15743659, 'M&M Signature Polo', 'Introducing the M&M Signature Polo, a stylish and versatile choice for men who appreciate quality and comfort. Made from premium cotton, this polo shirt features the iconic M&M logo subtly embroidered on the chest. With its classic design and impeccable craftsmanship, the M&M Signature Polo is perfect for both casual outings and more refined occasions, ensuring you stand out with effortless charm and sophistication.', 275, 'Mens', '61(1).png'),
(15743660, 'Soleil Cascade One-Shoulder Dress', 'The Soleil Cascade One-Shoulder Dress embodies understated elegance with its asymmetrical design and delicate beige strings. Crafted from flowing fabric, this dress drapes gracefully, accentuating the curves while exuding sophistication. Perfect for special occasions or evening events, the Soleil Cascade Dress effortlessly combines modern style with timeless allure, making you the epitome of chic refinement.', 250, 'Womens', '65(1).png'),
(15743661, ' Midnight Muse Leather Jacket', 'The Midnight Muse Leather Jacket is a statement piece designed to exude confidence and style. Crafted from premium leather, it features a sleek silhouette with asymmetrical zip closure and intricate stitching details. Whether paired with jeans for a casual look or worn over a dress for a night out, this jacket adds a touch of edgy sophistication to any outfit, making it a timeless staple in every woman\'s wardrobe.', 350, 'Womens', '69(1).png'),
(15743662, 'Arctic Breeze Polo', 'The Arctic Breeze Polo is a timeless classic that exudes effortless elegance. Crafted from high-quality cotton, this polo shirt features a crisp white hue that adds a touch of sophistication to any ensemble. With its clean lines, tailored fit, and subtle detailing, the Arctic Breeze Polo is perfect for both casual outings and more formal occasions, ensuring you look polished and refined wherever you go.', 450, 'Womens', '73.png'),
(15743663, 'Noir Chic Cropped Blazer', 'Elevate your ensemble with the Noir Chic Cropped Blazer, a sophisticated fusion of modern style and timeless elegance. Crafted from sleek black fabric, this cropped blazer features a tailored silhouette with sharp lapels and a single-button closure. Perfect for layering over a crop top or dress, it adds a touch of edge and sophistication to any outfit, making it the perfect choice for both casual and formal occasions.\r\n', 189, 'Womens', '79.png'),
(15743664, 'Midnight Elegance Long Sleeve', 'The Midnight Elegance Long Sleeve is a versatile wardrobe staple crafted from soft, luxurious fabric in classic black. With its figure-flattering fit and timeless design, this long sleeve top effortlessly transitions from day to night. Whether paired with jeans for a casual look or styled with trousers for a more polished ensemble, the Midnight Elegance Long Sleeve adds a touch of sophistication to any outfit, making it a must-have essential for every wardrobe.', 289, 'Mens', '81.png'),
(15743665, 'Cocoa Couture Bodycon Dress', ' The Cocoa Couture Bodycon Dress is a show-stopping piece designed to accentuate your curves with elegance. Crafted from stretchy, figure-hugging fabric in a rich brown hue, this dress features a sleek bodycon silhouette that flatters your shape. Perfect for evening events or special occasions, its understated yet sophisticated style ensures you stand out with effortless allure.', 369, 'Womens', '85.png'),
(15743666, 'Tropic Breeze Polo', 'The Tropic Breeze Polo captures the essence of Hawaiian inspiration with its vibrant colors and tropical motifs. Crafted from breathable fabric, this polo shirt features bold floral patterns and bright hues reminiscent of island paradises. Whether you\'re lounging by the beach or enjoying a casual outing, the Tropic Breeze Polo adds a touch of laid-back charm and vacation vibes to your ensemble, making it a perfect choice for warm-weather days.', 250, 'Mens', '89.png'),
(15743667, 'Azure Serenity Midi Dress', 'The Azure Serenity Midi Dress is a vision of elegance and grace in a captivating shade of blue. Crafted from flowing fabric, this dress features a flattering silhouette with a fitted bodice and a flowing midi-length skirt. Perfect for both formal events and casual occasions, its versatile design ensures you radiate timeless charm and sophistication wherever you go.', 500, 'Womens', '93.png'),
(15743668, 'Sandstone Classic Polo', 'The Sandstone Classic Polo seamlessly blends the timeless elegance of white with the warm richness of brown, creating a sophisticated and versatile piece. Crafted from high-quality cotton, this polo shirt features a classic design with a white body and brown accents on the collar and sleeves. Perfect for both casual outings and more formal occasions, the Sandstone Classic Polo exudes understated style and refined charm, making it a wardrobe essential for the modern gentleman.', 450, 'Mens', '97.png'),
(15743669, ' Sapphire Skies Mini Skirt', 'The Sapphire Skies Mini Skirt embodies youthful charm and effortless style with its vibrant shade of blue. Crafted from lightweight fabric, this skirt features a flirty silhouette that accentuates the legs and adds a playful touch to any ensemble. Perfect for both casual outings and evening adventures, the Sapphire Skies Mini Skirt promises to make a statement wherever you go, radiating confidence and chic flair.', 200, 'Womens', '36(2).png'),
(15743670, 'Crimson Court Tennis Skirt', 'The Crimson Court Tennis Skirt blends sporty functionality with chic style, perfect for the modern athlete. Crafted from moisture-wicking fabric, this skirt keeps you cool and comfortable during intense matches. Its vibrant red hue adds a pop of color to the court, while the pleated design offers freedom of movement and a flattering silhouette. Whether you\'re serving an ace or hitting the town, the Crimson Court Tennis Skirt ensures you play and look your best.', 235, 'Womens', '37(2).png'),
(15743671, ' Urban Slate Cargo Pants', 'The Urban Slate Cargo Pants offer a perfect blend of style and functionality for urban explorers. Crafted from durable, high-quality fabric, these cargo pants feature multiple pockets for convenient storage and a relaxed fit for all-day comfort. The neutral gray color adds versatility to your wardrobe, allowing you to pair them with a variety of tops for different looks. Whether you\'re running errands or embarking on an outdoor adventure, the Urban Slate Cargo Pants are a go-to choice for modern-day explorers.', 499, 'Mens', '41(2).png'),
(15743672, 'Slate Shadow Tennis Skirt', 'The Slate Shadow Tennis Skirt combines sporty elegance with classic sophistication. Crafted from lightweight, breathable fabric, this skirt offers freedom of movement on the court while keeping you cool and comfortable. Its subtle gray hue adds a touch of understated style, perfect for pairing with any tennis top or sports attire. Whether you\'re serving up aces or enjoying a casual match, the Slate Shadow Tennis Skirt ensures you look and feel your best with every swing.', 350, 'Womens', '45(2).png'),
(15743673, 'Earthy Elegance Pants', 'The Earthy Elegance Pants are a timeless wardrobe essential, offering both style and comfort in a rich brown hue. Crafted from high-quality fabric with a hint of stretch, these pants feature a tailored fit that flatters the silhouette while providing freedom of movement. Whether paired with a crisp shirt for a polished look or a casual tee for laid-back vibes, the Earthy Elegance Pants are perfect for any occasion, exuding sophistication and versatility.', 500, 'Mens', '49(2).png'),
(15743674, 'Breezy Blossom Mini Skirt', 'The Breezy Blossom Mini Skirt is a playful and flirty addition to your wardrobe, perfect for embracing sunny days with style. Crafted from lightweight fabric, this skirt features a flattering A-line silhouette that flows with every step. Its shorter length adds a touch of flirtation, while the vibrant floral pattern infuses your look with charm and energy. Whether paired with a crop top for a summer festival or a blouse for a casual outing, the Breezy Blossom Mini Skirt promises to elevate your ensemble with its effortless grace and femininity.', 389, 'Womens', '54(1).png');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=15743675;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
